# Generated by Django 3.1.7 on 2021-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanana', '0002_auto_20210301_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter a email of company (e.g. a@a.com)', max_length=254)),
                ('mobile', models.CharField(help_text='Enter a mobile of company (e.g. +919898257016)', max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TblEmail',
        ),
    ]
