# Generated by Django 3.1.7 on 2021-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanana', '0004_tblslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblslider',
            name='sliderimage',
            field=models.FileField(upload_to='images/'),
        ),
    ]
