# Generated by Django 3.1.7 on 2021-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanana', '0005_auto_20210301_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name (e.g. Ronak Panchal)', max_length=100)),
                ('designation', models.CharField(help_text='Enter a designation (e.g. Web Designer)', max_length=100)),
                ('social_fb', models.TextField(help_text='Enter a facebook link (e.g. fb/ronak)', max_length=500)),
                ('social_ln', models.TextField(help_text='Enter a linkedin link (e.g. Best Company)', max_length=500)),
                ('social_insta', models.TextField(help_text='Enter a instagram link (e.g. Best Company)', max_length=500)),
                ('social_twitter', models.TextField(help_text='Enter a twitter link (e.g. Best Company)', max_length=500)),
                ('sliderimage', models.FileField(upload_to='photo/')),
            ],
        ),
    ]
